name: ci nodejs app
on:
  push:
    branches:
     - main

jobs:
  build-nodejs-artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello nodejs app"
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20.x
      - name: install dependencies
        run: npm install
      - name: testing
        run: npm test
      - name: build artifact
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: dist
          path: dist/
          retention-days: 1

    





